### PR TITLE
Add features2 to IndexPackage

### PR DESCRIPTION
**Pull request by Stargateur**
Related to https://github.com/ehuss/cargo-index/issues/9, I'm sure it's cover all features2... features

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks for the PR! I think I would prefer to keep the `deny_unknown_fields`. It should be relatively easy to add the `features2` field. I think it should be `Option<BTreeMap<String, Vec<String>>>`.

**Comment by Stargateur** [comment]
`BTreeMap<String, Vec<String>>` should be enough since it's a container, None == Empty, thus I can use Option if you want.

I don't know what I should do here https://github.com/ehuss/cargo-index/blob/49828f89f976435837d3bb08dfd864d2ba57df09/reg-index/src/metadata.rs#L166-L175

what should `features2` init to ?

**Comment by ehuss** [comment]
I think it would be fine to have `features2` init to None.

**Comment by Stargateur** [comment]
This doesn't seem to work, for example:

```none
{
  "name": "lockable",
  "vers": "0.0.1",
  "deps": [
    {
      "name": "anyhow",
      "req": "^1.0.56",
      "features": [],
      "optional": false,
      "default_features": true,
      "target": null,
      "kind": "normal"
    },
    {
      "name": "lru",
      "req": "^0.7.5",
      "features": [],
      "optional": true,
      "default_features": true,
      "target": null,
      "kind": "normal"
    },
    {
      "name": "owning_ref_lockable",
      "req": "^0.4.2",
      "features": [],
      "optional": false,
      "default_features": true,
      "target": null,
      "kind": "normal"
    },
    {
      "name": "thiserror",
      "req": "^1.0.30",
      "features": [],
      "optional": false,
      "default_features": true,
      "target": null,
      "kind": "normal"
    },
    {
      "name": "tokio",
      "req": "^1.17.0",
      "features": [
        "sync",
        "rt"
      ],
      "optional": false,
      "default_features": true,
      "target": null,
      "kind": "normal"
    },
    {
      "name": "tokio",
      "req": "^1.17.0",
      "features": [
        "sync",
        "time",
        "macros",
        "rt-multi-thread"
      ],
      "optional": false,
      "default_features": true,
      "target": null,
      "kind": "dev"
    }
  ],
  "cksum": "d6ee43511e5ce3bbdf78b8a4a9c3fb2482c16114adf55259004b13fd5d62bb3a",
  "features": {},
  "features2": {
    "lru": [
      "dep:lru"
    ]
  },
  "yanked": false,
  "links": null,
  "v": 2
}
```

Fail to parse

**Comment by Stargateur** [comment]
Ahhhhh, there is a new field `"v": 2`

**Comment by Stargateur** [comment]
Do you prefer use an enum, having `V1` and `V2` or just a field `v` ?

**Comment by ehuss** [comment]
> Do you prefer use an enum, having `V1` and `V2` or just a field `v` ?

I think an `Option<u32>` would be fine.

**Comment by ehuss** [comment]
@Stargateur Just checking if you've had a chance to look at adding the `v` field?  I can work on it if you don't think you'll be able to.

**Comment by Stargateur** [comment]
done, do you prefer to skip serialization of Option field with `#[serde(skip_serializing_if = "Option::is_none")]` ?

**Comment by ehuss** [comment]
Oh, yea, good point. Yea, I think it would be good to add that for `features2` and `v`.  That is how [crates.io works](https://github.com/rust-lang/crates.io/blob/3081ba388cf6ae45fb87930264b9c3f28f643555/cargo-registry-index/lib.rs#L114-L139).

**Comment by Stargateur** [comment]
I added a integration tests and use skip if.

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
